Develop
urakovdanil/diploma-1 pull request #1
Opened 2024-05-01 07:34 UTC by urakovdanil

2024-05-07 20:06 UTC, Bazys requested changes
Нет ни одного юнит теста. Давай сделаем покрытие хотя бы в 40%

2024-05-07 20:06 UTC, Bazys commented on internal/accrual/client.go
> +		OnBeforeRequest(func(c *resty.Client, r *resty.Request) error {
Параметр функции, названный `c`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `c` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-05-07 20:06 UTC, Bazys commented on internal/logger/logger.go
> +		source := a.Value.Any().(*slog.Source)
а если там лежит совсем не то? может все таки проверять?

2024-05-07 20:06 UTC, Bazys commented on internal/accrual/client.go
> +func (cl *c) run() {
может все таки сюда передавать контекст, которым котнролировать работу самой горутины `run` она сейчас бесконтрольная.

2024-05-07 20:06 UTC, Bazys commented on internal/accrual/client.go
> +	ctx := context.WithValue(context.Background(), types.CtxKeyRequestID, ord.requestID)
плохая практика использовать контекст для значений. Извлечение этих значений из дерева контекста - дорогая операция.

2024-05-07 20:06 UTC, Bazys commented on internal/accrual/client.go
> +		time.Sleep(time.Duration(retryAfter) * time.Second)
Предпочтение, отдаваемое Go в определенных сценариях `time.NewTicker`, а не `time.Sleep`, обусловлено различиями в их использовании и природой параллельного программирования в Go. Обе функции являются частью пакета `time` и предоставляют механизмы для работы со временем, но они служат разным целям.

### `time.Sleep`

- **Назначение**: `time.Sleep` приостанавливает выполнение текущей goroutine по крайней мере на указанное время. Это простой способ задержать выполнение в одном месте вашего кода.
- **Польза**: Лучше всего использовать, когда вам нужна простая, одноразовая задержка, не требующая повторных действий или точного контроля времени после окончания задержки.
- **Поведение**: Блокирует работу goroutine, делая ее неактивной на время сна, без каких-либо дополнительных накладных расходов или механизма управления.

### `time.NewTicker`

- **Назначение**: `time.NewTicker` создает новый тикер, который будет отправлять время в свой канал через определенные промежутки времени. Он предназначен для тех случаев, когда вам нужно делать что-то многократно через регулярные промежутки времени.
- **Польза**: Это идеальный вариант для повторяющихся действий, когда вам нужно поддерживать постоянную скорость работы, например, для опроса или многократной проверки обновлений. Тикер предоставляет канал, по которому вы можете делать выборку, легко взаимодействуя с моделью параллелизма Go.
- **Поведение**: Позволяет более гибко управлять механизмом синхронизации. Вы можете остановить тикер, по сути, освободив его ресурсы и остановив интервальные операции. Этого нельзя добиться с помощью `time.Sleep`, поскольку sleep не предлагает механизма остановки.

### Сравнение и предпочтения

- **Конкурентность и контроль**: `time.NewTicker` лучше вписывается в модель параллелизма Go, предоставляя канал для диапазона или выбора. Это более идиоматично в Go при работе с повторяющимися действиями с таймером. Он предлагает больше контроля, позволяя вам остановить тикер и предотвратить дальнейшие тики, что невозможно с `time.Sleep`.
- **Управление ресурсами**: Тикеры можно останавливать и очищать, что особенно важно для долго работающих приложений, чтобы предотвратить утечку ресурсов. `time.Sleep` не потребляет дополнительных ресурсов во время сна, но он не предлагает такого контроля и гибкости, как тикеры.
- **Использование в циклах**: Для операций, которые должны выполняться через регулярные промежутки времени, предпочтительнее использовать `time.NewTicker`, поскольку он обеспечивает постоянный интервал между тиками, в то время как использование `time.Sleep` в цикле может привести к смещению во времени из-за времени выполнения основного блока цикла.

В итоге, если `time.Sleep` подходит для простых, разовых задержек, не требующих дополнительного контроля времени, то `time.NewTicker` предпочтительнее для задач, требующих повторного выполнения через фиксированные промежутки времени, предлагая больший контроль и интеграцию с парадигмами параллельного программирования Go. Выбор между `time.Sleep` и `time.NewTicker` зависит от конкретных потребностей вашего приложения в синхронизации и параллельности. 

---------

Go's preference for `time.NewTicker` over `time.Sleep` in certain scenarios stems from their different use cases and the nature of concurrent programming in Go. Both are part of the `time` package and provide mechanisms to deal with time, but they serve distinct purposes.

### `time.Sleep`

- **Purpose**: `time.Sleep` pauses the current goroutine for at least the duration specified. It's a straightforward way to delay execution in a single spot in your code.
- **Use Case**: It's best used when you need a simple, one-off delay with no need for repeated action or precise timing control after the sleep is over.
- **Behavior**: It blocks the goroutine, making it inactive for the duration of the sleep, without any additional overhead or control mechanism.

### `time.NewTicker`

- **Purpose**: `time.NewTicker` creates a new ticker that will send the time on its channel at intervals. It's designed for when you need to do something repeatedly at regular intervals.
- **Use Case**: It's ideal for repeated actions where you need to maintain a consistent rate of operation, like polling or repeatedly checking for updates. The ticker provides a channel that you can select on, integrating smoothly with Go's concurrency model.
- **Behavior**: It allows for more flexible control over the timing mechanism. You can stop a ticker, essentially freeing its resources and stopping the interval operations. This cannot be achieved with `time.Sleep` as sleep does not offer a stop mechanism.

### Comparison and Preference

- **Concurrency and Control**: `time.NewTicker` fits better into Go's concurrency model, providing a channel to range over or select on. This is more idiomatic in Go when dealing with repeated timed actions. It offers more control, allowing you to stop the ticker and prevent further ticks, something not possible with `time.Sleep`.
- **Resource Management**: Tickers can be stopped and cleaned up, which is particularly important in long-running applications to prevent resource leaks. `time.Sleep` does not consume additional resources while sleeping, but it does not offer the control and flexibility that comes with tickers.
- **Use in Loops**: For operations that must occur at regular intervals, `time.NewTicker` is preferred because it ensures a consistent interval between ticks, whereas using `time.Sleep` in a loop could lead to drift over time due to the execution time of the loop body.

In summary, while `time.Sleep` is suitable for simple, one-off delays without the need for further timing control, `time.NewTicker` is preferred for tasks that require repeated execution at fixed intervals, offering greater control and integration with Go's concurrent programming paradigms. The choice between `time.Sleep` and `time.NewTicker` depends on the specific timing and concurrency needs of your application.

2024-05-08 14:57 UTC, urakovdanil commented on internal/accrual/client.go
> +		OnBeforeRequest(func(c *resty.Client, r *resty.Request) error {
Ух ты, проморгал. 
Выбрал второй вариант - сигнатура функции регламентирована методом.

2024-05-08 15:00 UTC, urakovdanil commented on internal/logger/logger.go
> +		source := a.Value.Any().(*slog.Source)
Не совсем понимаю, о чем ты. 
Сам код взял из доки slog: https://pkg.go.dev/log/slog (`command+F` по `source := a.Value.Any().(*slog.Source)`)

2024-05-08 15:09 UTC, urakovdanil commented on internal/accrual/client.go
> +func (cl *c) run() {
Не согласен относительно бесконтрольности. 
Я организовал следующий пайплайн: 
1. При инициализации клиента запускается эта горутина, которая зацикливается на чтении из канала (https://github.com/urakovdanil/diploma-1/blob/1817514dea927f77569f8307e52a613cc622394e/internal/accrual/client.go#L135)
2. При завершении работы, после прекращения получения новых запросов, срабатывает глобальный клозер (https://github.com/urakovdanil/diploma-1/blob/1817514dea927f77569f8307e52a613cc622394e/cmd/gophermart/main.go#L83)
3. Сработавший глобальный клозер триггерит клозер клиента, который закрывает канал (https://github.com/urakovdanil/diploma-1/blob/1817514dea927f77569f8307e52a613cc622394e/internal/accrual/client.go#L38)
4. Закрытие канала освобождает горутину run(). 

Таким образом run полностью подконтрольна: запуск и остановка очевидны и опираются на стандарты языка. 

Поправь, пожалуйста, если я в чем-то ошибся.

2024-05-08 15:15 UTC, urakovdanil commented on internal/accrual/client.go
> +	ctx := context.WithValue(context.Background(), types.CtxKeyRequestID, ord.requestID)
О стоимости операции согласен, однако здесь постарался сделать все идиоматично: передавать данные, специфичные для запроса, в контексте, который распространяется по стеку вызовов. 
Идея была в том, чтобы поддержать внутренние идентификаторы запросов. Не стал настраивать нормальный трейсинг - реализовал так. 
Такая механика позволила свести всю обработку логов в одну функцию: 
https://github.com/urakovdanil/diploma-1/blob/1817514dea927f77569f8307e52a613cc622394e/internal/logger/logger.go#L69

2024-05-08 15:35 UTC, urakovdanil commented on internal/accrual/client.go
> +		time.Sleep(time.Duration(retryAfter) * time.Second)
Да, вспоминал об этой части доки, когда писал реализацию) 

Если я правильно тебя понял, мне стоит перейти на тикер. 

Не согласен: в коде выше Sleep используется для того, чтобы дождаться снятия блокировки на отправку запросов. За контроль фриза будет отвечать единственная горутина (уповаю на то, что вероятность одновременного прохода двух горутин через условие 
https://github.com/urakovdanil/diploma-1/blob/1817514dea927f77569f8307e52a613cc622394e/internal/accrual/client.go#L57
ничтожна). Помимо этого фриз - нерегулярное событие, а единовременное (или регулярное, но параметр Retry-After может меняться). Если аккруал не очухается после первого раза, то отправку зафризит другой запрос. 

Поправь, если я в чем-то ошибся, пожалуйста.

2024-05-12 18:24 UTC, Bazys commented on internal/logger/logger.go
> +		source := a.Value.Any().(*slog.Source)
а дальше? .(*slog.Source) вдруг не то и ты не сможешь скастить?
проверка на ok всегда полезна

2024-05-12 18:31 UTC, Bazys commented on internal/accrual/client.go
> +		time.Sleep(time.Duration(retryAfter) * time.Second)
при реализации через тикер, ты заодно еще сможешь отлавливать завершение через контекст.
Хотя если ты используешь контекст всего лишь для данных, то тогда нет смысла.

2024-05-12 18:34 UTC, Bazys commented on internal/accrual/client.go
> +func (cl *c) freezeSending(ctx context.Context, retryAfterHeaderValue string) {
функция-обертка вокруг анонимной лямбды. Не проще сам метод вызвать в горутине?

2024-05-12 18:39 UTC, Bazys commented on internal/accrual/client.go
> +	ctx := context.WithValue(context.Background(), types.CtxKeyRequestID, ord.requestID)
существует практика, когда сам логгер в контекст кладут, который уже обогащают данными типа request_id.
Но я не поддерживаю идею использования контекста кроме как для прерывания и максимум для user_id для аутентификации

2024-05-12 18:46 UTC, Bazys commented on internal/accrual/client.go
> +func (cl *c) run() {
в принципе использование `context.Background()` вне main уже плохая практика. Любой контекст должен наследоваться от контекста созданного один раз при старте приложения. И если бы ты передал сюда контекст, который прослушивает сигналы выхода из приложения, то можно было меньше писать свой код, а обрабатывать прерывание этого контекста во всех горутинах.

2024-05-12 18:47 UTC, Bazys approved these changes

2024-05-18 10:57 UTC, merged